### ISSUE TITLE
Doesn't work using 'sinc' upscale_mode

### ISSUE THREAD

**Issue by anne-o-pixel** [Ryu1845/YoloCR#8]
Hello

If I put `upscale_mode = 'sinc'` I have a problem:

```
Script evaluation failed:
Python exception: local variable 'ssbis' referenced before assignment

Traceback (most recent call last):
  File "src\cython\vapoursynth.pyx", line 2244, in vapoursynth.vpy_evaluateScript
  File "src\cython\vapoursynth.pyx", line 2245, in vapoursynth.vpy_evaluateScript
  File "YoloCR.py", line 369, in <module>
    yolocr.main()
  File "YoloCR.py", line 303, in main
    clip, self.crop_box_dimensions, crop_box_height, ss, ssbis
UnboundLocalError: local variable 'ssbis' referenced before assignment

pipe:: Invalid data found when processing input
```

**Comment by Ryu1845** [comment]
stupid logic error, fixed I think
